### ISSUE TITLE
Scheme submission: Zr

### ISSUE THREAD

**Issue by manuelraiwa** [RIMS-Code/rims-code.github.io#78]
{
    "notes": "Developed at LLNL, USA with SHG TiSas",
    "references": [
        {
            "author": "Raiwa and Savina",
            "id": "https://doi.org/10.1039/D4JA00065J",
            "year": 2024
        }
    ],
    "rims_scheme": {
        "scheme": {
            "element": "Zr",
            "gs_level": "0",
            "gs_term": "4d^{2}5s^{2} (^{3}F_{2})",
            "ip_term": "",
            "lasers": "Ti:Sa",
            "last_step_to_ip": false,
            "step_forbidden0": false,
            "step_forbidden1": false,
            "step_level0": "378.16",
            "step_level1": "369.727",
            "step_lowlying0": false,
            "step_lowlying1": false,
            "step_term0": "4d^{2}5s(a^{2}D)5p (^{4}F_{3})",
            "step_term1": "Rydberg",
            "trans_strength0": "",
            "trans_strength1": "",
            "unit": "nm"
        }
    },
    "saturation_curves": [
        {
            "data": {
                "x": [
                    0.0,
                    30000.0,
                    40000.0,
                    110000.0,
                    180000.0,
                    290000.0,
                    440000.0,
                    660000.0,
                    1150000.0,
                    4480000.0
                ],
                "x_err": [
                    0.0,
                    2000.0,
                    2000.0,
                    5000.0,
                    9000.0,
                    14000.0,
                    22000.0,
                    33000.0,
                    58000.0,
                    224000.0
                ],
                "y": [
                    0.0,
                    0.48,
                    0.663,
                    0.871,
                    0.849,
                    0.959,
                    0.847,
                    0.913,
                    0.985,
                    1.0
                ],
                "y_err": [
                    4e-05,
                    0.00205,
                    0.00256,
                    0.00312,
                    0.00306,
                    0.00334,
                    0.00305,
                    0.00323,
                    0.00341,
                    0.00345
                ]
            },
            "fit": true,
            "notes": "- <sup>90</sup>Zr normalized to 1.\n- Measured on LION at LLNL.  TiSa system.\n- FES Beam focus 1.2 x 1.4 mm, 1000 Hz, 6.9 ns Pulsewidth.\n- SES set to 369.730 nm ",
            "title": "FES ",
            "unit": "W * cm^-2"
        },
        {
            "data": {
                "x": [
                    0.0,
                    84000.0,
                    337000.0,
                    631000.0,
                    1157000.0,
                    1789000.0,
                    2210000.0,
                    2273000.0,
                    5261000.0
                ],
                "x_err": [
                    0.0,
                    4000.0,
                    17000.0,
                    32000.0,
                    58000.0,
                    89000.0,
                    110000.0,
                    114000.0,
                    263000.0
                ],
                "y": [
                    0.0001,
                    0.0247,
                    0.1377,
                    0.2577,
                    0.3539,
                    0.4396,
                    0.6087,
                    0.6673,
                    1.0
                ],
                "y_err": [
                    0.0,
                    0.0004,
                    0.0011,
                    0.0016,
                    0.0019,
                    0.0022,
                    0.0027,
                    0.0029,
                    0.0039
                ]
            },
            "fit": true,
            "notes": "- SES beam focused to 1.1 x 1.1 mm, 1000 Hz, 5 ns pulsewidth.\n- Signal <sup>90</sup>Zr normalized to 1.",
            "title": "SES",
            "unit": "W * cm^-2"
        }
    ],
    "submitted_by": "Manuel Raiwa"
}

**Comment by trappitsch** [comment]
A few notes (mostly bugs in processing)

- Submission mask makes a json error (https://github.com/RIMS-Code/rimsdb_scheme_submission/issues/13)
- Put comments in as bullet points
- Remove "Draw to IP feature" (https://github.com/RIMS-Code/rimsdb_scheme_submission/issues/14)
- Power units were entered in MW/cm2 and not in W/cm2 (need more unit selections in submission mask) (https://github.com/RIMS-Code/rimsdb_scheme_submission/issues/15)
- Entry of states should be fixed now. Needs a better description as well.
